# Generated by Django 5.1.2 on 2025-05-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_voice_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='voice_message',
            field=models.FileField(blank=True, null=True, upload_to='voice_messages/'),
        ),
    ]
