# Generated by Django 5.1.2 on 2025-06-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='gif_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_gif',
            field=models.BooleanField(default=False),
        ),
    ]
