# Generated by Django 5.1.2 on 2025-06-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_attachment_fields'),
        ('chat', '0006_message_gif_url_message_is_gif'),
    ]

    operations = [
    ]
