# Generated by Django 5.1.2 on 2025-06-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_merge_20250610_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='emoji_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_emoji',
            field=models.BooleanField(default=False),
        ),
    ]
